# Importing All The Model Building Libraries

In [35]:
pwd

'/home/wsuser/work'

In [2]:
!pip install keras==2.2.4
!pip install tensorflow

     |████████████████████████████████| 312 kB 24.9 MB/s eta 0:00:01
     |████████████████████████████████| 50 kB 20.3 MB/s eta 0:00:01
  Attempting uninstall: keras
    Found existing installation: keras 2.7.0
    Uninstalling keras-2.7.0:
      Successfully uninstalled keras-2.7.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.7.2 requires keras<2.8,>=2.7.0, but you have keras 2.2.4 which is incompatible.
     |████████████████████████████████| 1.3 MB 22.0 MB/s eta 0:00:01
  Attempting uninstall: keras
    Found existing installation: Keras 2.2.4
    Uninstalling Keras-2.2.4:
      Successfully uninstalled Keras-2.2.4


In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MaxAbsScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.metrics import f1_score
import pickle


# reading train and test dataset

In [4]:

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='4zdc_CjgpF4rUb1Hy66H1Pw8DtZoOw_nDg-3W1JB8rUt',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'smartlender-donotdelete-pr-luukgx3bidqosk'
object_key = 'test.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

test = pd.read_csv(body)
test.head()


Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        1           1          1              0             3500   
1       1        1           0          0              0            11146   
2       1        0           0          0              0             5849   
3       1        0           0          0              0             2833   
4       1        1           3          0              0             6406   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0             1083.0  135.000000             360.0               1   
1                0.0  136.000000             360.0               1   
2                0.0  146.412162             360.0               1   
3             1857.0  126.000000             360.0               1   
4                0.0  150.000000             360.0               1   

   Property_Area  Loan_Status  
0              2            1  
1              2            1  
2              2            1  
3              0            1  
4              1            0

In [5]:

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='4zdc_CjgpF4rUb1Hy66H1Pw8DtZoOw_nDg-3W1JB8rUt',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'smartlender-donotdelete-pr-luukgx3bidqosk'
object_key = 'train.csv'

body = cos_client.get_object(Bucket=bucket,Key=object_key)['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

train = pd.read_csv(body)
train.head()


Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       0        0           0          0              0             5000   
1       0        0           0          1              0             2165   
2       1        1           2          0              0            16666   
3       0        0           0          0              0             5417   
4       1        1           0          0              0             4583   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0             2541.0       151.0             480.0               1   
1                0.0        70.0             360.0               1   
2                0.0       275.0             360.0               1   
3                0.0       143.0             480.0               0   
4             5625.0       255.0             360.0               1   

   Property_Area  Loan_Status  
0              0            0  
1              1            1  
2              2            1  
3              2            0  
4              1            1

In [6]:
scaler = MaxAbsScaler()

In [7]:
train_y = train.iloc[:,-1]

In [8]:
train_x = train.drop('Loan_Status',axis=1)

In [9]:
test_y = test.iloc[:,-1]

In [10]:
test_x = test.drop('Loan_Status',axis=1)

In [11]:
x = pd.concat([train_x,test_x],axis=0)
y = pd.concat([train_y,test_y],axis=0)

In [12]:
train_x = scaler.fit_transform(train_x)

In [13]:
test_x = scaler.transform(test_x)

## Decision Tree Model

In [14]:
def decisionTree(train_x,test_x,train_y,test_y):
    dt = DecisionTreeClassifier()
    dt.fit(train_x,train_y)
    y_pred = dt.predict(test_x)
    print("**** Decision Tree Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

In [15]:
decisionTree(train_x,test_x,train_y,test_y)

**** Decision Tree Classifier ****
Confusion Matrix
[[24 14]
 [20 65]]
Classification Report
              precision    recall  f1-score   support

           0       0.55      0.63      0.59        38
           1       0.82      0.76      0.79        85

    accuracy                           0.72       123
   macro avg       0.68      0.70      0.69       123
weighted avg       0.74      0.72      0.73       123



## Random Forest Model

In [16]:
def randomForest(train_x,test_x,train_y,test_y):
    rf = RandomForestClassifier()
    rf.fit(train_x,train_y)
    y_pred = rf.predict(test_x)
    print("**** Random Forest Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

In [17]:
randomForest(train_x,test_x,train_y,test_y)

**** Random Forest Classifier ****
Confusion Matrix
[[20 18]
 [ 5 80]]
Classification Report
              precision    recall  f1-score   support

           0       0.80      0.53      0.63        38
           1       0.82      0.94      0.87        85

    accuracy                           0.81       123
   macro avg       0.81      0.73      0.75       123
weighted avg       0.81      0.81      0.80       123



## KNN Model

In [18]:
def knn(train_x,test_x,train_y,test_y):
    knn = KNeighborsClassifier()
    knn.fit(train_x,train_y)
    y_pred = knn.predict(test_x)
    print("**** KNeighbour Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

In [19]:
knn(train_x,test_x,train_y,test_y)

**** KNeighbour Classifier ****
Confusion Matrix
[[16 22]
 [ 2 83]]
Classification Report
              precision    recall  f1-score   support

           0       0.89      0.42      0.57        38
           1       0.79      0.98      0.87        85

    accuracy                           0.80       123
   macro avg       0.84      0.70      0.72       123
weighted avg       0.82      0.80      0.78       123



## Xgboost Model

In [20]:
def xgboost(train_x,test_x,train_y,test_y):
    xg = GradientBoostingClassifier()
    xg.fit(train_x,train_y)
    y_pred = xg.predict(test_x)
    print("**** Gradient Boosting Classifier ****")
    print('Confusion Matrix')
    print(confusion_matrix(test_y,y_pred))
    print('Classification Report')
    print(classification_report(test_y,y_pred))

In [21]:
xgboost(train_x,test_x,train_y,test_y)

**** Gradient Boosting Classifier ****
Confusion Matrix
[[16 22]
 [ 3 82]]
Classification Report
              precision    recall  f1-score   support

           0       0.84      0.42      0.56        38
           1       0.79      0.96      0.87        85

    accuracy                           0.80       123
   macro avg       0.82      0.69      0.71       123
weighted avg       0.81      0.80      0.77       123



## Evaluating Performance Of The Model

In [22]:
rf = RandomForestClassifier()
rf.fit(train_x,train_y)
ypred = rf.predict(test_x)


In [23]:
f1_score(ypred,test_y,average='weighted')

0.8225019669551534

In [24]:
cv = cross_val_score(rf,x,y,cv=5)

In [25]:
np.mean(cv)

0.7964680794348927

## Saving The Model

In [26]:
pickle.dump(rf,open('rdf.pkl','wb'))
pickle.dump(scaler,open('scale.pkl','wb'))

# IBM Deployment

In [27]:
!pip install -U ibm-watson-machine-learning

In [29]:
from ibm_watson_machine_learning import APIClient
import json

# Authenticate and Set Space

In [32]:
wml_credentials={
    "apikey": "g9bGmoW9_jtSp9DcTiVZOCOyxcFLSvYG8DLIKyFpcSXt",
    "url":"https://us-south.ml.cloud.ibm.com"
}

In [33]:
wml_client = APIClient(wml_credentials)
wml_client.spaces.list()

Note: 'limit' is not provided. Only first 50 records will be displayed if the number of records exceed 50
--  ----  -------
ID  NAME  CREATED
--  ----  -------


In [36]:
wml_client.spaces.list()

Note: 'limit' is not provided. Only first 50 records will be displayed if the number of records exceed 50
------------------------------------  ------------  ------------------------
ID                                    NAME          CREATED
35590be5-9411-4956-84d6-c7264718d562  smart_lender  2022-11-15T15:51:45.414Z
------------------------------------  ------------  ------------------------


In [37]:
SMART_ID="35590be5-9411-4956-84d6-c7264718d562"